#====================================
# ipm
#====================================
ipm:
  name: IPM-Collector
  version: 0.1.1
  # license
  license: TEST000000

#====================================
# spring
#====================================
spring:
  # amqp
  rabbitmq:
    host: shinwootnskr.iptime.org
    port: 5672
    username: admin
    password: shinwoo123!
    virtual-host: /

#====================================
# banner
#====================================
banner:
  charset: UTF-8
  location: classpath:banner.txt

#====================================
# logging
#====================================
logging:
  file: /logs/ipm-collector.log
  level:
    org.springframework: INFO
    level.com.shinwootns: DEBUG
    root: INFO
