#====================================
# ipm
#====================================
ipm:
  name: IPM-Collector(Debug Mode)
  version: 0.1.1
  license: TEST000000
  redis:
    host: shinwootnskr.iptime.org
    port: 6379
    password: 7+AzHIrmzGDARTT1VaQa3Q==
    timeout: 0
  rabbitmq:
    host: shinwootnskr.iptime.org
    port: 5672
    username: admin
    password: 7+AzHIrmzGDARTT1VaQa3Q==
    virtual-host: /
  
  # debug mode
  debug_enable: true
  debug:
    enable_recv_syslog: false

#====================================
# spring
#====================================
#spring:
  #rabbitmq:
    #host: shinwootnskr.iptime.org
    #port: 5672
    #username: admin
    #password: shinwoo123!
    #virtual-host: /

#====================================
# banner
#====================================
banner:
  charset: UTF-8
  location: classpath:banner.txt

#====================================
# logging
#====================================
logging:
  file: /logs/ipm-collector.log
  level:
    org.springframework: INFO
    level.com.shinwootns: DEBUG
    root: INFO
