#====================================
# ipm
#====================================
ipm:
  name: IPM
  version: 0.1.1
  license: TEST000000
  cluster:
    mode: master    # master, slave
    slave-index: 0  # 0 ~ 99
    
#====================================
# Security
#====================================
security:
  user:
    name: admin
    password: shinwoo123!

#====================================
# spring
#====================================
spring:
  # db
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://shinwootnskr.iptime.org:5432/ipm_db
    username: postgres
    password: shinwoo123!
    max-idle: 10
    testOnBorrow: true
    validation-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddlAuto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  # amqp
  rabbitmq:
    host: shinwootnskr.iptime.org
    port: 5672
    username: admin
    password: shinwoo123!
    virtual-host: /
  # Redis
  redis:
    host: shinwootnskr.iptime.org
    port: 6379
    password: shinwoo123!
    timeout: 0
    

#====================================
# banner
#====================================
banner:
  charset: UTF-8
  location: classpath:banner.txt

#====================================
# server
#====================================
server:
  port: 8080
  session:
    timeout: 3000

#====================================
# logging
#====================================
logging:
  file: /logs/ipm-manager.log
  level:
    org.springframework: INFO
    level.com.shinwootns: DEBUG
    root: INFO

#====================================
# mybatis
#====================================
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml