#====================================
# ipm
#====================================
ipm:
  name: Smart IPM
  version: 0.1.1
  license: TEST000000
  security:
    user: admin
    password: 7+AzHIrmzGDARTT1VaQa3Q==
  cluster:
    mode: slave       # master, slave
    slave-index: 100  # 0 ~ 9999
  redis:
    host: shinwootnskr.iptime.org
    port: 6379
    password: 7+AzHIrmzGDARTT1VaQa3Q==
    timeout: 0
  rabbitmq:
    host: shinwootnskr.iptime.org
    port: 5672
    username: admin
    password: 7+AzHIrmzGDARTT1VaQa3Q==
    virtual-host: /

#====================================
# Security
#====================================
#security:
#  user:
#    name: admin
#    password: shinwoo123!

#====================================
# spring
#====================================
spring:
  # db
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://shinwootnskr.iptime.org:5432/ipm_db
    username: postgres
    password: shinwoo123!
    max-idle: 10
    testOnBorrow: true
    validation-query: SELECT 1
  jpa:
    show-sql: false
    hibernate:
      ddlAuto: none
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

#====================================
# banner
#====================================
banner:
  charset: UTF-8
  location: classpath:banner.txt

#====================================
# server
#====================================
server:
  port: 8080
  session:
    timeout: 3000

#====================================
# logging
#====================================
logging:
  file: /logs/ipm-manager.log
  level:
    org.springframework: INFO
    com.shinwootns: INFO
    root: INFO

#====================================
# mybatis
#====================================
mybatis:
  config-location: classpath:/mybatis/mybatis-config.xml